services:
  SS_Database:
    image: "postgres:latest"

    ports:
      - 5432:5432

    networks:
      - postgres-network

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

    volumes:
      - ${PWD}/ss_database/:/var/lib/postgresql/data/
      - ${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  postgres-network:
    driver: bridge
